### PR TITLE
Allow test descriptions (describe, it, unroll, fit, fdescribe) to be longer than 140 characters

### PR DESCRIPTION
**Pull request by Blackbaud-JasonBodnar**

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
Hey @Blackbaud-JasonBodnar.  I'm having a hard time duplicating what this is attempting to fix.

For comments and regular code I am able to see the linting errors.  However, for long strings, tslint seems ok with it being longer 140 characters.

Screen Shot 2020-01-06 at 3 50 04 PM

I believe this is because the default value of `check-strings` is false.  https://palantir.github.io/tslint/rules/max-line-length/

Since the describe/it/etc. names would be strings, I'm not seeing why this change would be necessary.

Thanks for any more info you're able to provide.

**Comment by Blackbaud-JasonBodnar** [comment]
@Blackbaud-BobbyEarl : Here's a link to a branch of our project with the lint error:

https://blackbaud.visualstudio.com/Products/_git/skyux-spa-donation-forms?version=GBlong_test_name_example_for_bobby_earl_DO_NOT_MERGE

In IntelliJ, I get the following with a long test name:

image

And running `skyux lint` I see:

```
$ skyux lint
SKY UX is processing the 'lint' command.
TSLint started synchronously.
/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/src/app/donation-details/recent-donations-list/recent-donations-list.component.spec.ts:160:1
ERROR: 160:1   max-line-length  Exceeds maximum line length of 140
```

**Comment by Blackbaud-BobbyEarl** [comment]
Thanks for the additional details @Blackbaud-JasonBodnar.

`tslint` introduced the `check-strings` property under the `max-line-length` rule in [`v5.19.0`](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v5190).  Your SPA is currently running `5.12.1`.

I confirmed I saw the linting error in your SPA. Ugrading to the latest version of tslint does indeed remove linting error regarding the long test name..

I don't think this PR is necessary any more.

**Comment by Blackbaud-JasonBodnar** [comment]
Yup. Upgrading tslint gets rid of the warning. Thanks @Blackbaud-BobbyEarl !

**Pull request closed without merging**
