### PR TITLE
Allow user to pass in browser args with --browserArgs when running skyux serve

### PR DESCRIPTION
**Pull request by Blackbaud-JasonBodnar**
#196

### CODE REVIEW

**Comment by Blackbaud-JasonBodnar** [comment]
Note: With bash on Linux you can't do `skyux test --browser google-chrome --browserArgs '--incognito'`. Bash sees the `--` in `--incognito` and thinks it's an argument it should handle. Instead you have to do `skyux test --browser google-chrome --browserArgs='--incognito'`. Not sure how other shells or OS's will handle things.

**Comment by Blackbaud-BobbyEarl** [comment]
@Blackbaud-JasonBodnar can you clarify whether you expect this code change to work for `skyux test` (as your comment says) or only for `skyux serve`?

**Comment by Blackbaud-JasonBodnar** [comment]
Oops. This is only for `skyux serve`. Typo in the comment above. I'll see if I can edit it.

**Comment by Blackbaud-BobbyEarl** [comment]
Outside of builder, I can't get this functionality to work properly.  Looking at the examples in the [open package](https://github.com/sindresorhus/open). For example the following code does in fact open Chrome, but it opens the URL in the first window and not the incognito window.

```
const open = require('open');
 
(async () => {
    await open('https://bobbyearl.com', {app: ['google chrome', '--incognito']});
})();
```

Digging in some more, I see that script (for my OS) ultimately calls the following:

```
open -a 'google chrome' 'https://bobbyearl.com' --args --incognito
```

A slight modification; however, does allow me to have the desired behavior:

```
open -a 'google chrome' --args 'https://bobbyearl.com' --incognito
```

This may require digging in more or filing an issue in their rep.

Having said all of that, I went down this path as I'm not sure this PR is necessary given how the [minimist package](https://github.com/substack/minimist) processes arguments in to arrays.  For example, you could use the following technique to pass additional arguments to the `app` property of open from builder.

```
skyux serve --browser='google-chrome' --browser='--incognito'
```

**Comment by Blackbaud-JasonBodnar** [comment]
Yup:

`skyux serve --browser='google-chrome' --browser='--incognito'`

worked for me. I'll close this and open a PR to update the docs with that info.

**Pull request closed without merging**
